### ISSUE TITLE
Left-side is readonly?

### ISSUE THREAD

**Issue by retailcoder** [Vogel612/TranslationHelper#37]
The UI doesn't make it very clear that the left-hand side resx is readonly, and the resx to edit goes on the right-hand side.

It's not necessarily a problem, but then there should be a one-click button to swap the two sides.

**Comment by retailcoder** [comment]
Just noticed the sides can be swapped by dragging-and-dropping. nice touch.

**Comment by Vogel612** [comment]
@retailcoder while the sides can be swapped by dragging and dropping, I didn't actually expect that to work :+1:   
If it does clear the read-only-ness of the root locale, I'd consider it a big bug. I assume it wouldn't work in the swing UI.

Then again, since the read-only seems undesirable, I might as well remove that

**Comment by retailcoder** [comment]
> Then again, since the read-only seems undesirable, I might as well remove that

That would be nice; basically you could fix a typo or rephrase the "reference" resource strings while going through them for translation.
